server.port: 8081
#spring:
#  kafka:
#    bootstrap-servers: localhost:9092
kafka-consumer:
  bootstrap-servers: localhost:9092
  auto-offset-reset: earliest

  #ms
  request-timeout: 60000

  #ms
  session-timeout: 30000

  retry-attempt: 3
  retry-backoff-period: 3000

app:
  topic:
    example: topic.01

logging:
  level:
    root: WARN
    org.springframework.web: INFO
    com.memorynotfound: DEBUG