server.port: 8081
#spring:
#  kafka:
#    bootstrap-servers: localhost:9092
kafka-consumer:
  bootstrap-servers: localhost:9092
  auto-offset-reset: earliest


app:
  topic:
    example: topic.01

logging:
  level:
    root: WARN
    org.springframework.web: INFO
    com.memorynotfound: DEBUG