server.port: 8082
#spring:
#  kafka:
#    bootstrap-servers: localhost:9092
kafka-producer:
  bootstrap-servers: localhost:9092

app:
  topic:
    example: topic.01

logging:
  level:
    root: WARN
    org.springframework.web: INFO
    com.memorynotfound: DEBUG